### ISSUE TITLE
URLs voor RSS 2.0 en Atom 1.0

### ISSUE THREAD

**Issue by teusink** [Gertje823/datalekt-feed#2]
Beste Gertje823,

Ik ben de ontwikkelaar van DataLekt en kwam jouw project hier tegen. Ik heb inmiddels twee exports voor RSS en Atom. De inhoud heb ik daarop ook aangepast.

Wellicht kun je hiermee je script(s) verder verbeteren, mocht je dat willen. Het zou in ieder geval het parsen van HTML schelen, en je bent zekerder van dat er geen wijzigingen optreden die je script breken.

https://www.datalekt.nl/feeds/rss.php
https://www.datalekt.nl/feeds/atom.php

**Comment by Gertje823** [comment]
Hi Joram,

Leuk om te zien dat Datalekt nu zelf een RSS feed heeft.
Aangezien de RSS feed op de site waarschijnlijk sneller bijwerkt dan mijn feed, is deze repo nu een beetje overbodig.

Ik zal de repo archiveren en in de readme verwijzen naar de RSS feed van Datalekt.nl
